# Generated by Django 4.0.4 on 2022-05-21 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('number', models.IntegerField()),
                ('address', models.CharField(max_length=250)),
                ('qualification', models.CharField(choices=[('BSC NURSING', 'BSC NURSING'), ('STAFF NURSE', 'STAFF NURSE')], max_length=250)),
            ],
        ),
    ]
