# Generated by Django 4.0.4 on 2022-05-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_doctor_photo_alter_doctor_number_alter_nurse_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='number',
            field=models.IntegerField(),
        ),
    ]
