# Generated by Django 4.0.4 on 2022-05-23 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_department'),
        ('staff', '0005_alter_doctor_number_alter_nurse_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ManyToManyField(to='hospital.department'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='department',
            field=models.ManyToManyField(to='hospital.department'),
        ),
    ]
